FROM centos:7

#MAINTAINER Nadav Ben Mazia nadavbm@outlook.com

RUN useradd docker_root

WORKDIR /home/docker_root

#RUN mkdir .ssh && /
#    chmod 700 -R .ssh/ && /
#    touch .ssh/authorized_keys
#    chmod 600 .ssh/authorized_keys

#ADD key.bash .ssh/

#RUN ls -lash .ssh/ && /
#    cd .ssh/ && /
#    bash key.bash

#EXPOSE 22

#CMD[echo, whoami]
