---

- name: Add Jenkins repository
  shell: wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo

- name: Install Jenkins with rpm
  shell: rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key

- name: Install Jenkins and Java packages
  yum: name={{ item }} state=present
  with_items:
    - jenkins
    - java
  ignore_errors: yes

- name: Enable Jenkins daemons
  service: name={{item}} enabled=yes
  with_items:
    - jenkins
  ignore_errors: yes

- name: Restart Jenkins daemons
  service: name={{item}} state=restarted enabled=yes
  with_items:
    - jenkins
  ignore_errors: yes

- name: Check Jenkins configuration
  shell: chkconfig jenkins on
