---

- name: Add installation source REMI
  shell: rpm -Uvh http://rpms.remirepo.net/enterprise/remi-release-7.rpm
  ignore_errors: yes

- name: Install yum utils
  shell: yum -y install yum-utils
  ignore_errors: yes

- name: Yum updates
  shell: yum -y update
  ignore_errors: yes

- name: Config managet - Enable REMI php 7.1
  shell: yum-config-manager --enable remi-php71
  ignore_errors: yes

- name: Install all PHP 7.1 packages
  yum: name={{ item }} state=latest
  with_items:
        - php
        - php-opcache
        - php-fpm
        - php-pdo
        - php-mbstring
        - php-xml
        - php-common
        - php-cli
        - php-zip
  ignore_errors: yes

- name: Restart nginx and php-fpm services
  service: name={{item}} state=restarted
  with_items:
    - nginx
    - php-fpm
  ignore_errors: yes

- name: Add Index.php page to nginx
  template:
    src: index.php.j2
    dest: /usr/share/nginx/html/index.php
    owner: root
    group: root
    mode: 0755

# Take a look at this link to install different versions of PHP
# https://www.tecmint.com/install-php-7-in-centos-7/
#
# Just change the Config Manager to enable REMI php 7.x as follow:
## yum-config-manager --enable remi-php70   [Install PHP 7.0]
## yum-config-manager --enable remi-php71   [Install PHP 7.1]
## yum-config-manager --enable remi-php72   [Install PHP 7.2]
#

