---

- name: Create direcotry for swarm install files and working directory
  shell: mkdir -p /storage/docker/install && mkdir -p /storage/docker/overlay && mkdir -p /storage/docker/images/1 && mkdir -p /storage/docker/images/2
  ignore_errors: yes

- name: Add yum config repo
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  ignore_errors: yes

- name: Download docker packages
  get_url:
    url: "{{ URL }}"
    dest: "{{ DIR }}"
    mode: 0440
  ignore_errors: yes

- name: Install docker package
  shell: yum install {{ DIR }}/docker-ce-18.09.0-3.el7.x86_64.rpm -y
  ignore_errors: yes

- name: Install docker
  yum: name={{ item }} state=latest
  with_items:
        - docker-ce
        - docker-ce-cli
        - container.io
  ignore_errors: yes

- name: Enable docker service
  service: name={{item}} enabled=yes
  with_items:
    - docker-ce
  ignore_errors: yes

- name: Start docker service
  service: name={{item}} state=started
  with_items:
    - docker
  ignore_errors: yes

- name: install docker-py package with pip
  pip: ame={{ item }} state=present
  with_items:
    - docker
    - docker-py
  ignore_errors: yes

