version : '3.2'

services:
  web:
    build: './web'
    ports:
      - 80:80
    expose: ["80"]
    dns: 
      - 8.8.8.8
      - 8.8.4.4
    environment:
      SOME_ENV: qa
    depends_on:
      - db
    links:
      - db
    networks:
      default:
        external:      
          name: frontend

  db:
    image: mysql:5.6
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Pa$$w0rd
      MYSQL_DATABASE: someDB
      MYSQL_USER: someUser
      MYSQL_PASSWORD: Pa$$w0rd
    volumes:
      - /var/lib/mysql
      - ./_data:/var/lib/mysql
    networks:
      backend:
