---

- name: Install nginx package
  yum: name={{ item }} state=latest
  with_items:
    - nginx
  ignore_errors: yes

- name: Start nginx
  service: name={{ item }} state=started
  with_items:
    - nginx

- name: Enable nginx service
  service: name={{ item }} enabled=yes
  with_items:
    - nginx
  ignore_errors: yes

- name: Add nginx configuration to /etc
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0755

