---

  - name: Install Maria-DB on CentOS7
    yum: name={{ item }} state=latest
    with_items:
          - mariadb-server
          - mariadb
    ignore_errors: yes

  - name: Enable mariadb service
    service: name={{item}} enabled=yes
    with_items:
      - mariadb
    ignore_errors: yes

  - name: Start mariadb service
    service: name={{item}} state=started
    with_items:
      - mariadb
    ignore_errors: yes

  - name: Copy mysql_secure_installation script to the server
    template:
      src: mysql_secure_installation.sh.j2
      dest: /root/mysql_secure_installation.sh
      owner: root
      group: root
      mode: 0755
    ignore_errors: yes

  - name: Run secure installation by Script (Define root password under "vars")
    shell: cd /root && ./mysql_secure_installation.sh
    ignore_errors: yes

