URL: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-18.09.0-3.el7.x86_64.rpm
##    URL: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-18.09.0.ce-1.el7.centos.x86_64.rpm
DIR: /data/docker/install
USER: root
