---

- name: Install docker swarm on CentOS 7
  hosts: docker
  remote_user: root
  become: yes
  vars:
    URL: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-18.09.0-3.el7.x86_64.rpm
#    URL: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-18.09.0.ce-1.el7.centos.x86_64.rpm
    DIR: /data/docker/install
    USER: root
  tasks:
########################### Common Packages ################################

  - name: Install common packages
    yum: name={{ item }} state=latest
    with_items:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
          - iptables
    ignore_errors: yes

############################# Firewall Rules ################################
  - name: Disable firewalld
    systemd: 
      name: firewalld
      state: stopped
      enabled: no

  - name: Add iptable configuration file
    template:
      src: files/iptables.j2
      dest: /etc/sysconfig/iptables
      owner: root
      group: root
      mode: 0644
    ignore_errors: yes

  - name: Configure persistent Port Forwarding to Docker
    template:
      src: files/sysctl.conf.j2
      dest: /etc/sysctl.conf
      owner: root
      group: root
      mode: 0644
    ignore_errors: yes

  - name: Reload IPtables
    service: name={{item}} daemon_reload=yes
    with_items:
      - iptables
    ignore_errors: yes

############################# Install Docker #################################
  - name: Remove all docker packages
    shell: yum remove -y docker docker-client docker-client-latest docker-common docker-latest docker-latest-logrotate docker-logrotate docker-selinux  docker-engine-selinux docker-engine
    ignore_errors: yes

  - name: Get docker repository
    shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    ignore_errors: yes

  - name: Create data dirs
    shell: mkdir -p /data/docker/{git,registry,install} && mkdir -p /data/docker/registry/{certs,auth,images}
    ignore_errors: yes

  - name: Download docker packages
    get_url:
      url: "{{ URL }}"
      dest: "{{ DIR }}"
      mode: 0440
    ignore_errors: yes

  - name: Install docker package
    shell: yum install {{ DIR }}/docker-ce-18.09.0-3.el7.x86_64.rpm -y
    ignore_errors: yes

  - name: Yum install docker
    yum: name={{ item }} state=latest
    with_items:
          - docker-ce
          - docker-ce-cli
          - container.io
          - docker-compose
    ignore_errors: yes

  - name: Enable Docker service
    service: name={{item}} enabled=yes
    with_items:
      - docker
    ignore_errors: yes

  - name: Start docker service
    service: name={{item}} state=started
    with_items:
      - docker
    ignore_errors: yes

  - name: Docker info check
    shell: docker info

  - name: Docker info check
    shell: docker container --help && docker --version
    ignore_errors: yes
