---

- name: Disable firewalld
  service: name={{item}} enabled=yes
  with_items:
    - firewalld
  ignore_errors: yes

- name: Stop firewalld
  service: name={{item}} state=stopped
  with_items:
    - firewalld
  ignore_errors: yes

- name: Add iptable configuration file
  template:
    src: files/iptables.j2
    dest: /etc/sysconfig/iptables
    owner: root
    group: root
    mode: 0644
  ignore_errors: yes

- name: Configure persistent Port Forwarding to Docker
  template:
    src: files/sysctl.conf.j2
    dest: /etc/sysctl.conf
    owner: root
    group: root
    mode: 0644
  ignore_errors: yes

- name: Reload IPtables
  service: name={{item}} daemon_reload=yes
  with_items:
    - iptables
  ignore_errors: yes
