---

- hosts: swarm
  remote_user: root
  become: yes
  become_method: sudo
  tasks:
    - name: epel-release install
      shell: yum install -y epel-release
    - name: Install pip
      yum: name=python-pip state=present
      ignore_errors: yes
    - name: install docker-py package
      pip: name=docker-py
      ignore_errors: yes

    - name: Copy Docker Image to swarm
      template:
        src: docker/Dockerfile
        dest: /storage/docker/images/Dockerfile
        mode: 644
        owner: root
        group: root
      ignore_errors: yes
   
    - name: Build docker image from Dockerfile
      shell: cd /storage/docker/images && docker build -t quandoo .
      ignore_errors: yes
    
    - name: List images
      shell: docker image ls -a

    - name: run the site in a docker container
      shell: docker run -d quandoo

    - name: Check if container is running
      shell: docker ps
