---

- name: Add user and deploy SSH Keys for SSH authentication
  hosts: swarm
  remote_user: nadav.benmazia
  become: yes
  vars:
    user: userName
  tasks:
  - name: Add Authotized_keys file to .ssh folder
    template:
      src: files/{{ user }}/authorized_keys.j2
      dest: /home/{{ user }}/.ssh/authorized_keys
      owner: '{{ user }}'
      group: '{{ user }}'
      mode: 0600

  - name: Get id_rsa.pub key as an output
    shell: cat /home/{{ user }}/.ssh/id_rsa.pub
    ignore_errors: yes

  - name: Get authorized keys output
    shell: cat /home/{{ user }}/.ssh/authorized_keys
    ignore_errors: yes
